Added in forgotten dependency requirement for brew-explorer

diff --git a/dtools b/dtools
--- a/dtools
+++ b/dtools
@@ -23486,6 +23486,20 @@ dtools_tui_misc_brew_explorer_parse_requirements() {
 		esac
 	done
 
+	missing_deps=
+
+	if ! command -v brew-explorer >/dev/null 2>&1; then
+		printf "missing dependency: brew-explorer\n" >&2
+		printf "%s\n\n" "See 'https://github.com/cosmincatalin/brew-explorer'" >&2
+		missing_deps=1
+	else
+		deps['brew-explorer']="$(command -v brew-explorer | head -n1)"
+	fi
+
+	if [[ -n $missing_deps ]]; then
+		exit 1
+	fi
+
 	action="tui misc brew-explorer"
 
 	while [[ $# -gt 0 ]]; do
